chancejs/chancejs

chance.js
test/test.helpers.js

Providing a weight of 0 to weighted() would cause a division by zero and ultimately failure of the helper.
Fixes #138

Fix division by zero with weights of zero

---

Gruntfile.js
chance.js
package.json
test/base.js
test/test.address.js
test/test.helpers.js
test/test.misc.js
test/test.person.js
test/test.time.js

This PR includes a lib bump for `grunt-contrib-jshint` as well as general JSHint updates and cleanup.
- Removing deprecated JSHint options
- Adding `undef: true` & `unused: true` Enforcements
- Code cleanup

JSHint cleanup, fixes, and improvements

---

bin/chance.js

If stdout/stderr is a TTY, emit a newline so that running the CLI from the prompt still looks nice. Piping into another process (head, less, etc.) will still omit the newline.

Add newline to output if stdout/err is a tty

---

chance.js

Problem... calling `Chance` without `seed` results in passing `undefined` as seed, and therefore similar outputs. Executing...
console.log([Chance().random(),Chance().random(),Chance().random(),Chance().random()])
... results in ...
[0.548813502304256, 0.548813502304256, 0.548813502304256, 0.548813502304256]
If we change that to call chance with `seed` only if defined, we get...
[0.901146336691454, 0.249545892002061, 0.3616938649211079, 0.3616938649211079]
... which is much better, but there is still a problem. Last two items are identical. Seems that when `MersenneTwister` is initialised without `seed`, it uses microsecond resolution timestamp as seed - so two calls in the same microsecond produce the exact same result. By changing the seed definition (when not specified as parameter) to …

when Chance called as function, only call new chance with seed if defined, and use random integer instead of time when no seed specified for twister

---

chance.js
test/test.basic.js

By passing the options, this allows character() to leverage the same options as string()

Provide same options for string as character #152 

---

chance.js
test/test.person.js

Adding a function to create an MRZ (Machine Readable Zone) found on Passports. Correctly generates the check digits and can generate completely random and valid passport data. Check digit algorithm is in the public domain. Checked with UK passports and has a couple of test cases asserting output against output from http://www.emvlab.org/mrz/. Have used output from this module to successfully verify age for a well known online betting company (who I work for).

Add passport number generator

---

chance.js

Multiple calls to initOptions function prevented default values to affect the option variable's min and max values.
This fixes bug #176.

Fix bug #176, where range(longitude) == range(latitude)

---

Gruntfile.js
chance.js
test/test.web.js

Include a way to easily generate md5 hashes and (gr)avatar urls.
Sample usage:
```javascript
// md5()
chance.md5(); // = <random hash>
chance.md5('value'); // = 2063c1608d6e0baf80249c42e2be5804
// md5() w/all options
chance.md5({ str: 'value', key: 'key', raw: true }); // = 'C>ý_2~¤³DW,gö
// avatar()
chance.avatar(); // = //www.gravatar.com/avatar/<random hash>
chance.avatar('email@test.com'); // = //www.gravatar.com/avatar/f1f97cfa813c828a73528989da671a81
// avatar() w/all options
chance.avatar({
email: 'email@test.com', 
protocol: 'https', // http or https. Otherwise client determinate.
fileExtension: 'png', // bmp, gif, or jpg. Otherwise no specification.
rating: 'g', // g, pg, r, or x. Otherwise no specification.
fallback: 'retro', // 404, mm, identicon, monsterid, wavatar, retro, …
```

Add md5() and avatar() methods

---

chance.js

In using this library, I thought it would be nice to add in an option to change and/or remove the punctuation mark at the end of a sentence. This would make it ideal for generating random things like alert messages that you may want to have end with an exclamation mark instead of a period, or page titles where you may want no punctuation mark at all.

Change or remove punctuation mark from sentence

---

web/_posts/1900-01-01-color.md

Fixed markdown for '0x', and changed `three` to `four`

Fixed color base types

---

chance.js
test/test.file.js
test/test.web.js

Extend color functionality:
================================
Sometimes I need to work with valid html color values as names (like red, green, blue etc) in my projects. So I added a little functionality that provide random real color name to the users of chance.
Also I added some extended comments to the color functionality looking forward for an approval to add more comments this makes reading development code easy in my opinion.
Add file generator:
================================
I created a simple random file generator which return a random file string with random extension.
The user can specify the extension or provide a collection of external extensions. Currently the method is using an extension pull for most common file types (raster / vector / documents etc)
With this commit I …

Extend color functionality with real name format option

---

chance.js

Allow capitalize to be passed as an option to `word` or `syllable` methods.

Adds capitalize option to word and syllable

---

chance.js
test/test.normal.js

Hi All. This new functionality would allow users to generate values other than numbers, but still based on the probabilities of a normal distribution. For example, let's say you were generating fake data for a vehicle manufacturer which makes 20 different models of cars and you wanted to generate those models based on a standard distribution pattern. Some of those models would be rare and others would be much more common. You can now do that by supplying a "pool" of values to the normal function:
```javascript
chance.normal({ mean: 9, dev: 3, pool: ['WRX', 'XV', 'BRZ', 'X', 'etc...'] });
```
Or in the case where you wanted a large array of them:
```javascript
chance.n(chance.normal, 1000, { mean: 9, dev: 3, pool: ['WRX', 'XV', 'BRZ', 'X', 'etc...'] });
```
This makes it slightly easier …

Add "pool" capability to normal() function

---

chance.js

Fixes chance.file() not working properly when a definition other than chance is used.

Fix chance.file() using chance.word internally instead of this.word

---

chance.js

On certain values, `chance.weighted` will throw the error `RangeError: Chance: Min cannot be greater than Max.` One example is calling `chance.weighted(['a', 'b'], [0.1551542617907946, 0])`.
The error is related to scaling the values into integers, where certain values multiplied by their multiplicative inverse yield `0.9999999999999999` instead of `1`.
This patch removes the scaling as it doesn't seem to be necessary, instead using `chance.random` scaled to the sum of the unscaled weights.

Fix Weighted for Edge Cases

---

chance.js
test/test.person.js

Fix for #255, the issue I just opened. Instead of generating a random year, month, and day, this change generates a random number of milliseconds since 1970/01/01 such that the resulting birthday is within the specified age range. I also fixed/changed some of the age ranges.

More accurate random birthday when using the type option

---

chance.js

When generating random dates without any options via `chance.date()`, the hour value is created with `this.hour()`, which by default generates an 12h value between 1 and 12. 
The expectation for date is (presumably) that it can generate any random date and time, not just times limited to AM hours. Note that this is already the behavior when providing `min` and `max` options, because it picks a random integer epoch within the bounds.
Distribution of hours before the fix (100k dates generated):
Distribution of hours after the fix (100k dates generated):

use "twentyfour" hour option when generating dates

---

chance.js

Added the functionality to get a random UTC Timezone. 
```
chance.timezone();
=> {"name": "India Standard Time", "abbr": "IST", "offset": 5.5, "isdst": false, "text": "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", "utc": ["Asia/Calcutta"]}
```
I have taken UTC Timezone data from here : https://github.com/dmfilipenko/timezones.json/blob/master/timezones.json
Thanks!

Added Timezones functionality

---

chance.js
test/test.helpers.js

chance.weighted(['a','b','c','d'],[NaN, 100, 1, 1]) always returns 'd'. 
fixed by throwing an error if any weight is NaN

weighted with NaN weight returns unexpected results

---

chance.js
test/test.file.js

One of the options for `chance.file()` is to specify the extension of the file, either via a single string or an array or object of strings. However, these were referenced as "extention" and it made it very confusing to use. This set of changes fixes this and updates the corresponding tests.

Fixed "Extension" Typos for chance.file

---

chance.js
test/test.web.js

Changes `chance.fbid()` so it returns a "numeric string".
- `yarn install`
- `yarn test`
- This is a breaking change as it irreversibly alters existing functionality.
- This makes return type of `chance.fbid()` both consistent with [chance.js's documentation](http://chancejs.com/#fbid) and [Facebook Graph API ](https://developers.facebook.com/docs/graph-api/reference/user/) documentation.
Fixes #328

Change Facebook ids format from integer to string

---

chance.js
test/test.address.js

This pull request adds to the chance.phone() method the option to generate numbers in brazilian format (br). The implementation was based on official documentation from **Brazil** that can be found on the **Anatel** website:
Mobile phone: http://www.anatel.gov.br/setorregulado/plano-de-numeraca-euileiro?id=330
Telephone: http://www.anatel.gov.br/setorregulado/plano-de-numeraca-brasileiro?id=331
I hope this can be useful.

Adding brazilian (br) phones support

---

chance.js
test/test.web.js

Added `chance.image` to get random images from [Lorem Picsum](https://picsum.photos/)

Get Random Image 

---

chance.js

Using let and const breaks many builds that don't yet support `let` and `const`

Change es6 variables to es5

---

chance.js
test/test.basic.js

Allows you to combine  `alpha`, `numeric` and `symbols` options.
```js
let token = chance.string({length: 64, alpha: true, numeric: true});
```

allow combination of alpha, numeric and symbols

---

chance.js
test/test.helpers.js

This improves the performance of `pickset` while continuing to provide a unique pick of elements from the array.
`pickset` in the console on the [website](http://chancejs.com) (currently v1.0.13) would not return more items than the length of the array, so I created a test for that restriction to avoid errors with this implementation.
Fixes #335 #336

improving pickset performance while returning unique values

---

chance.js

Delete `.` from the end of `Collections Manager`

Remove extraneous period

---

docs/web/url.md

Usage examples for protocol and domain_prefix are missing.

Add missing usage examples for url method

---

docs/miscellaneous/dice.md

Makes it explicit that the dice methods return a minimum of 1 since several developers on my team thought we had to guard against these methods returning 0 with patterns like `chance.d6() + 1`.

Adds note that dice methods have a min. value of 1

---

chance.js

Chance currently does not work in ie 11 because it uses const and for of
These usages can be replaced by var and for in

fix: make chance js work in es5 environment

---

chance.js
docs/text/paragraph.md
test/test.text.js

Closes [Issue #338](https://github.com/chancejs/chancejs/issues/338).
Added the option of line break to chance.paragraph();
Now it is possible to pass **{ linebreak: true }** as an option.
`chance.paragraph({ linebreak: true })`
The output:
> Teve mowohfu lopmaha iw za utacas mat ko muoka de olidaw fabolpo me.
Utecozo dauturap mudwij fefofkij mijvooce gazgab ju nezil uh eri ru binombaj.
Fugesbo ru vi nirab bo uruviv uwiwe upmubuso zoasa naguoci eske iledowva barawajip.  
Instead of:
> Teve mowohfu lopmaha iw za utacas mat ko muoka de olidaw fabolpo me. Utecozo dauturap mudwij fefofkij mijvooce gazgab ju nezil uh eri ru binombaj. Fugesbo ru vi nirab bo uruviv uwiwe upmubuso zoasa naguoci eske iledowva barawajip.
My first contribution and pull request :+1: 
@victorquinn

feature(paragraph): add line break option

---

docs/basics/string.md

There is a small typo in docs/basics/string.md.
Should read `length` rather than `lentgh`.

docs: Fix simple typo, lentgh -> length

---

chance.js
docs/location/coordinates.md
docs/location/latitude.md
docs/location/longitude.md
test/test.address.js

Up to now chancejs supports only one type of coordinates format, which is **Decimal Degrees (DD)**.
In reality there are more popular types of formats:
> **Degrees, Decimal Minutes (DDM)**:
> 47°38.938
> 122°20.887
> **Degrees, Minutes, Decimal Seconds (DMS)**:
> 47°38’56.26”
> 122°20’53.20”
> **Decimal Degrees (DD)**:
> 47.64896
> -122.34811
This PR adds the support of those two additional formats.
So we can write:
`chance.latitude({format: 'ddm'}) / chance.latitude({format: 'ddm'})`
`chance.latitude({format: 'dms'}) / chance.longitude({format: 'dms'})`
`chance.latitude({format: 'dd'}) / chance.longitude({format: 'dd'})`
When **format** is not specified, it will be default to **DD format**, so it won't cause any retroactive damage.
Examples:
`chance.latitude({format: 'ddm'})
--> …

feat(latitude-longitude): add format option

---

chance.js

#486 https://github.com/chancejs/chancejs/issues/486#issue-685096293
remove "let" identifier for compatible with old browsers

remove "let" identifier

---

chance.js
docs/location/phone.md
test/test.address.js

Option to specify an example number with an area code of '555' specifically for US.
chance.phone({ country: 'us', exampleNumber: true });
=> '(555) 927-2152'

Add "555" area code option

---

packages/chance/package.json
packages/chance/src/main.test.ts
packages/chance/src/main.ts
packages/falsy/README.md
packages/falsy/package.json
packages/falsy/src/main.test.ts
packages/falsy/src/main.ts
packages/falsy/tsconfig.json
packages/falsy/tslint.yaml

I figured this would be a good small start to test the waters. I essentially copied your bool package and modified it to be equivalent to your falsy code from your 1.X `chance.js` file. I left your package.json w/ author and license and all in place, only modifying tags and dependencies. Comments were sourced from your docs and I filled in the blanks where needed. **There is one breaking change**: Your default pool in 1.X didn't actually include `undefined`. I added it to match the docs. Anything missing? Is there anywhere you wanted contributors to sign off?

Added falsy generator

---

chance.js
test/test.time.js

This PR adds a failing test for the issue described in #484 and also updates all the timezone data to the latest version available from the documented source (which fixed the failing test).

Update timezone data, add missing utc fields

---

chance.js
docs/web/mac.md
test/test.web.js

Adds the ability to randomly generated Network MAC addresses (6 octets) with the ability to specify the MAC address delimiter.
If there is enough demand we could also add the ability to specify an OUI or generate an EUI-64 address (8 octet based MAC for non-network devices).

Add MAC address function

---

docs/person/cpf.md

The `formatted` option exists in the implementation but is currently not mentioned anywhere in the docs.

Add unformatted CPF example to docs

---

packages/chance/src/main.test.ts
packages/chance/src/main.ts

I went and checked out the `2.0` branch, but when running `yarn test` I ran into some import sort errors which prevented the rest of the build from completing. This PR fixes those errors so that the build step can complete properly.
@victorquinn would you consider adding some pre-commit hook to run `yarn test`? [Husky](https://github.com/typicode/husky/tree/master) is pretty easy add add in.

🚨 fix import sort errors

---

docs/person/first.md

The docs state that 'us' and 'it' are the only values that can be assigned to the nationality parameter for chance.first().
1) 'us' is NOT accepted and results in an error. 'en' works fine instead.
2) 'nl' and 'fr' have been added in the meantime.
Code reference: https://github.com/chancejs/chancejs/blob/b3658c9c2161fc8c500ceadd87741a53e4a235d6/chance.js#L2797
I ran into the issue that 'us' threw an error in my code, hence I tracked the issue back to the docs and fixed it.
There are some other pull requests adding new nationalities to chance.first() which have not been considered yet in this change.

Fixed error in docs for chance.first()

---

packages/bool/src/main.ts
packages/falsy/src/main.test.ts
packages/falsy/src/main.ts
packages/integer/src/main.test.ts
packages/integer/src/main.ts

Looking at the 1.0 version of the `integer` generator, and the documentation comment for the generator, it should accept an options object as parameters, rather than 2 numbers as currently implemented in v2. i.e. it currently uses `integer(25, 100)`, but is documented to use `integer({ min: 25, max: 100 })`
This PR corrects the input shape to be an object.
```js
/**
*  Return a random integer
*
*  NOTE the max and min are INCLUDED in the range. So:
*  chance.integer({min: 1, max: 3});
*  would return either 1, 2, or 3.
*
*  @param {Object} [options={}] can specify a min and/or max
*  @returns {Number} a single random integer number
*  @throws {RangeError} min cannot be greater than max
*
```

♻️ refactored integer generator to accept object as param

---

chance.js

fixes issue #522
it was picking undefined coz index was wrong

fix: falsy returns undefined when it's not in pool

---

.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
package.json
test/test.music.js
yarn.lock

- This is a first step in fixing the broken github action pipelines.
- Currently there is a duplicate devDependencies key in the package.json. This is causing only 'gulp-uglify-es' to be installed when you run ```yarn``` 
-  I have also bumped the Node versions to be tested against from 9,10,12 to 12,14,16
-  Bumped the node version for the other pipeline steps to 16
*** This PR may not fix the pipelines but will give me enough information to get a fix together. Currently the pipelines dont even get past the test step ***
- The opposite. The pipelines are currently broken and this is a first step to a fix
Actions running successfully on my fork

Bumping Node version and fixing Github Actions failures

---

chance.js
test/test.basic.js

* Added a test that did not pass using the existing code. Using a double digit value in the exclude array broke the sorting logic in the chance.natural code.
* Fixed the sorting logic in chance.natural() and verified that the code works as intended.
* None
Acceptance Criteria:
If a number is included in the `exclude` array, then that number should not be returned from chance.natural().
For example: `chance.natural({ min: 3, max: 20, exclude: [9, 18]})`, should never return 9.
Before changes were made, 9 was returned from chance.natural():
After changes were made, 9 is never returned from chance.natural():

[BUG FIX] Fix exclusion of values in chance.natural()
