chancejs/chancejs

.gitignore, Gruntfile.js, bower.json, package.json, test/base.js, test/bower.json, test/test.basic.js
- Dependency updates & cleanup
- Adding JS sourcemap for `chance.min.js`
=> Dependency updates and cleanup

chance.js, test/test.web.js
I wanted the ability to create random rgba values for use in my project, and thought it may be a nice addition to the chance project as a while.
=> Added rgba generator.

chance.js, test/test.helpers.js
On branch pick-count-equals-1
Changes to be committed:
modified:   chance.js
modified:   test/test.helpers.js
See #166
=> `pick()` with count should return array

chance.js
These suffixes are commonly used in India for engineering graduates
=> Added B.E and B.TECH name suffixes

README.md
=> added info about json-schema-faker

chance.js, test/test.regional.js
**pl_nip** - generates NIP number used by Polish Tax Office
**pl_regon** - generates REGON number
**pl_pesel** - generates PESEL - national identification number
All these numbers are generally random with properly generated control sum. 
When validated - they are all correct
=> added Polish specific number generators

chance.js, test/test.person.js
AminaG. Create a valid Israel ID.
I have create the function, and the tests.
You can also test it here:
http://www.flex.co.il/Calculators/%D7%9E%D7%97%D7%A9%D7%91%D7%95%D7%9F-%D7%A1%D7%A4%D7%A8%D7%AA-%D7%91%D7%99%D7%A7%D7%95%D7%A8%D7%AA-%D7%AA%D7%A2%D7%95%D7%93%D7%AA-%D7%96%D7%94%D7%95%D7%AA.aspx
=> AminaG. Create a valid Israel ID

chance.js, test/test.address.js
https://en.wikipedia.org/wiki/Mariana_Trench
10,994 m (± 40 m)
=> Fix max depth

location/_posts/1900-01-01-state.md
Documenting PR #196 which addresses #195
=> Document us_states_and_dc option

chance.js, test/test.address.js
=> Add us_states_and_dc option to states()

test/test.basic.js
The reasoning and code to compute the probability is here:
https://gist.github.com/BlaMaeda/cfd886f84dd093cb2ead
=> Calculate the probability of a test failing

chance.js, test/test.helpers.js
Add pickone and pickset as discussed in https://github.com/victorquinn/chancejs/issues/205
=> Pickone and pickset

location/_posts/1900-01-01-phone.md
Came across this option after looking through the source. Figured it'd be helpful in the docs.
=> Add documentation for disabling formatted phone

company/_posts/1900-01-01-cnpj.md
Documentation for Company, adding cnpj function.
=> Doc company first script

README.md
Add mocker-data-generator module to the Readme
=> Add mocker-data-generator to the Readme.md

chance.js, test/test.company.js
Hello. 
I implemented another brazillian number generator: **CNPJ**.
It's like a **CPF**, but for companies instead citizens.
@victorquinn:
- How can I contribute updating documentation?
- Who should to update the minified javascript file?
Thank you
=> CNPJ generator added

chance.js
- doesn't modify source arrays
- detects array with zero total weight
- will not throw RangeError if values array is larget than weights array as this is not a problem
- faster (doesn't use array .reduce or .some)
=> modified weighted function

chance.js
If set, it will remove the chosen item from the source arrays. The default behaviour if no parameter supplied is unchanged ie, no trim.
=> Added optional 'trim' parameter to weighted function.

.gitignore, chance.js, test/test.person.js
See issue #258 - thought it would be fun to add.
Couldn't get the test suite running on my system, so let's hope this PR passes with flying colors ;-)
=> Add support for extra genders

chance.js
I corrected the missing semicolon from my prev. commit.
=> Added Hungarian ID number,typo corrected

chance.js, test/test.web.js
Generates a port number between 0 and 65535 which I based on the [wikipedia page for Port](https://en.wikipedia.org/wiki/Port_(computer_networking))
=> added port() to web section

chance.js
Added some logic for valid South African phone numbers and mobile numbers
=> adding logic for South African phone numbers and Mobile numbers

test/test.basic.js
Increment counter if the value of the random natural is zero or greater.
=> Natural can be zero

person/_posts/1900-01-01-name.md
=> Person API - name: nationality us changed for en

miscellaneous/_posts/1900-01-01-guid.md
=> Misc. API - guid: indication of version option

README.md
Because I think that project is awesome and perfectly leverages Chance with smooth integration and great results :)
=> README: add swagger-mock-api to libs using Chance

README.md
Added [fony](https://github.com/captainsafia/fony) to list of dependent tools. It is "a simple command line tool for generating fake data from a template string" by Safia Abdalla.
=> Added fony to list of dependent tools

chance.js
Added the capability to define a new seeded Chance in webworker.
Before you only could use chance, not create a newly seeded Chance.
=> Full Chance functionality in WebWorker

chance.js, test/test.basic.js
Adds a numerals option using powers of 10.
This will destroy the min/max options for natural if a numerals count
is passed.
=> Implements Issue #295

time/_posts/1900-01-01-weekday.md, web/_posts/1900-01-01-company.md, web/_posts/1900-01-01-profession.md
document weekday, company and profession from #333
=> document weekday, company and profession

chance.js, test/test.music.js
Added note(), midi_note(), chord(), chord_quality(), tempo()
I'm new to this, let me know if there's any problems. Hopefully this will come in handy - the first time I saw Chance.js in action was for something music-related so I was surprised to see no music functions in there.
Also, I'd be happy to write the documentation for these.
=> Added generators for music: notes, chords, tempos

chance.js, test/test.buffer.js
Add `chance.buffer` to generate random Buffer.
=> Add random buffer generation

chance.js, test/test.person.js
Added aadhar number generator, which is unique identifier specific to residents in India. Wrote test cases covering the respective code
=> Added aadhar number generator

docs/text/syllable.md
=> Fix minor typo

test/test.address.js
=> 😞 I committed sloppy code

chance.js, docs/basics/natural.md, package-lock.json, package.json, test/test.basic.js
Closes #330 (Exclude option in Natural)
/cc @victorquinn 
Thanks!
=> Add natural exclude option

docs/README.md, docs/location/locale.md
the links to the specs were derived from the comments in the code
=> doc: add locale documentation

docs/person/last.md
Update docs for last usage, remove us (invalid option).  Add known valid options.
=> docs (last): Update usage for nationality. Remove us (not valid option)

docs/music/note.md, docs/music/tempo.md
Documentation for the note function
=> Note Documentation

chance.js, docs/README.md, docs/basics/falsy.md, package-lock.json, test/test.basic.js
This implementation meets the request of the issue #360 
I created a method "falsy()" to return one value of array default [false, null, undefined, 0, NaN, ''], or other value if the pool parameter  is used.
=> Adding method to return a falsy value

chance.js, docs/basics/template.md, test/test.basic.js
Adding support for templates eg:
```
vehicleId = chance.template('AAA###');
```
=> Add "template" function

docs/miscellaneous/unique.md
changes comparator function param to match reference
=> updates typo in code snippet

docs/basics/falsy.md
- A few small changes to the docs for `falsy`
=> Correct name for falsy docs

packages/mersenne-twister/src/main.test.ts
Just making the test title more descriptive.
=> Add clarity to MarsenneTwister test

package.json, yarn.lock
=> 🔨 added pre-commit hook

chance.js, docs/miscellaneous/fileWithContent.md, test/test.fileWithContent.js
Added a function to generate a file with random name, extension and content. 
Added tests.
Added docs.
=> Resolves issue 301 - Added file generator

chance.js
There was an unneccessary double space on HEX_POOL declaration.
=> Removed unneccessary double space.

docs/web/color.md
Hi! I found that these format options work. I would prefer if these were documented features, that's all.
=> Update color documentation with `rgba` and `name`
